### ISSUE TITLE
[BUG] Ysoserial not working 

### ISSUE THREAD

**Issue by 0xSp3ctra** [ThePorgs/Exegol-images#234]
### Describe the bug

When using the web tool Ysoserial, used for deserialization attacks, an error occurs : 

```bash
[Sep 08, 2023 - 14:49:14 (CEST)] exegol-web ~ # ysoserial CommonsCollectionsX "cmd"          
Error while generating or serializing payload
java.lang.IllegalAccessError: class ysoserial.payloads.util.Gadgets (in unnamed module @0x6f2fd062) cannot access class com.sun.org.apache.xalan.internal.xsltc.trax.TemplatesImpl (in module java.xml) because module java.xml does not export com.sun.org.apache.xalan.internal.xsltc.trax to unnamed module @0x6f2fd062
	at ysoserial.payloads.util.Gadgets.createTemplatesImpl(Gadgets.java:102)
	at ysoserial.payloads.CommonsCollections4.getObject(CommonsCollections4.java:32)
	at ysoserial.payloads.CommonsCollections4.getObject(CommonsCollections4.java:26)
	at ysoserial.GeneratePayload.main(GeneratePayload.java:34)
```
I've read that Yso have this issue with Java < 16, even the Ysoserial program in Exegol seems to use Java 11 : 

```bash
[Sep 08, 2023 - 14:53:49 (CEST)] exegol-web ~ # alias | grep yso
ysoserial='JAVA_HOME=/usr/lib/jvm/java-11-openjdk java -jar /opt/tools/ysoserial/ysoserial.jar'
```

A fix to that issue is to use some flags : 

```bash
java --add-opens=java.xml/com.sun.org.apache.xalan.internal.xsltc.trax=ALL-UNNAMED --add-opens=java.xml/com.sun.org.apache.xalan.internal.xsltc.runtime=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -jar ysoserial-all.jar URLDNS https://collaborator-url-here/
```

And after that the commands works : 

```bash
[Sep 08, 2023 - 14:54:22 (CEST)] exegol-web ~ # java --add-opens=java.xml/com.sun.org.apache.xalan.internal.xsltc.trax=ALL-UNNAMED --add-opens=java.xml/com.sun.org.apache.xalan.internal.xsltc.runtime=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -jar /opt/tools/ysoserial/ysoserial.jar CommonsCollectionsX "cmd"
rO0ABXNyABdqYXZhLnV0aWwuUHJpb3JpdH<REDACTED>IAAHhwc3IAO29y
```

Is it possible to fix the alias to add the flags or even change the Java version ?
For more infos : https://forum.portswigger.net/thread/ysoserial-stopped-working-b5a161f42f
Thanks for your work.

### Steps To Reproduce

```bash
ysoserial CommonsCollectionsX "cmd"
```

### Exegol Wrapper Version

```Text
> exegol version -vvv
[*] Exegol is currently in version v4.2.5
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[+] We thank Capgemini for supporting the project (helping with dev) 🙏                                                                                                                                            
[+] We thank HackTheBox for sponsoring the multi-arch support 💚                                                                                                                                                   
[D] Pip installation: On ✔                                                                                                                                                                                         
[D] Git source installation: Off 🪓                                                                                                                                                                                
[D] Host OS: HostOs.LINUX (DockerEngine.LINUX)                                                                                                                                                                     
[D] Arch: amd64                                                                                                                                                                                                    
[D] Raw arch: x86_64                                                                                                                                                                                               
[D] Docker desktop: Off 🪓                                                                                                                                                                                         
[D] Shell type: HostOs.LINUX                                                                                                                                                                                       
[D] Last wrapper update check: 2023-09-08 00:00:00
```

### Exegol container information

```Text
> exegol info -vv web
[*] Exegol is currently in version v4.2.5
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[+] We thank Capgemini for supporting the project (helping with dev) 🙏                                                                                                                                            
[+] We thank HackTheBox for sponsoring the multi-arch support 💚                                                                                                                                                   
[V] Listing user configurations                                                                                                                                                                                    

🧠 User configurations                                     
┌─────────────────────────────────────────────────────────┐
│ User config file: /home/osiris/.exegol/config.yml       │
│ Private workspace: /home/osiris/.exegol/workspaces      │
│ Exegol resources: /home/osiris/.exegol/exegol-resources │
│ My resources: /home/osiris/.exegol/my-resources         │
│ Auto-check updates: On ✔                                │
│ Auto-remove images: On ✔                                │
│ Auto-update fs: Off 🪓                                  │
│ Default start shell: zsh                                │
│ Shell logging method: asciinema                         │
│ Shell logging compression: On ✔                         │
└─────────────────────────────────────────────────────────┘

[V] Listing git repositories                                                                                                                                                                                       
[!] Exegol has not been installed via git clone. Skipping wrapper auto-update operation.                                                                                                                           
[*] If you have installed Exegol with pip, check for an update with the command pip3 install exegol --upgrade                                                                                                      
[!] Exegol has not been installed via git clone. Skipping wrapper auto-update operation.                                                                                                                           
[*] If you have installed Exegol with pip, check for an update with the command pip3 install exegol --upgrade                                                                                                      

🐙 Project modules                            
┌───────────┬───────────────┬────────────────┐
│ Name      │ Status        │ Current branch │
├───────────┼───────────────┼────────────────┤
│ Wrapper   │ Not installed │ ? 🤷           │
│ Images    │ Not installed │ ? 🤷           │
│ Resources │ Up to date    │ main           │
└───────────┴───────────────┴────────────────┘


⭐ Container summary                                                                    
┌──────────────────┬───────────────────────────────────────────────────────────────────┐
│             Name │ web                                                               │
│            Image │ web - v.3.1.1 (Up to date) (amd64)                                │
├──────────────────┼───────────────────────────────────────────────────────────────────┤
│    Creation date │ 08/09/2023 14:30                                                  │
│              GUI │ On ✔                                                              │
│          Network │ host                                                              │
│         Timezone │ On ✔                                                              │
│ Exegol resources │ On ✔ (/opt/resources)                                             │
│     My resources │ On ✔ (/opt/my-resources)                                          │
│    Shell logging │ Off 🪓                                                            │
│       Privileged │ Off ✔                                                             │
│        Workspace │ Dedicated (/workspace)                                            │
│             Envs │ DISPLAY=:0                                                        │
│                  │ _JAVA_AWT_WM_NONREPARENTING=1                                     │
│                  │ QT_X11_NO_MITSHM=1                                                │
│                  │ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin │
│          Volumes │ /tmp/.X11-unix ➡ /tmp/.X11-unix                                   │
│                  │ /etc/timezone ➡ /etc/timezone (RO)                                │
│                  │ /etc/localtime ➡ /etc/localtime (RO)                              │
│                  │ /home/osiris/.exegol/my-resources ➡ /opt/my-resources             │
│                  │ /home/osiris/.exegol/exegol-resources ➡ /opt/resources            │
│                  │ /home/osiris/.exegol/workspaces/web ➡ /workspace                  │
└──────────────────┴───────────────────────────────────────────────────────────────────┘
```

**Comment by ShutdownRepo** [comment]
should be fixed in the next nightly release
