### ISSUE TITLE
OpenSSL: unsupported hash type md4

### ISSUE THREAD

**Issue by DeserranoJorden** [ThePorgs/Exegol-images#306]
### Describe the bug

Recently when using the newest version and image of exegol in a clean ubuntu VM:

I get the `ValueError: unsupported hash type md4` error on multiple tools.
Some python tools, but the most annoying one is for example ldapdomaindum.

I’ve searched for the error on multiple github pages. And It all seems to be related to the OpenSSL library depricating some older hashing types. 

### Steps To Reproduce

As shown in the evidence, I’m running a full image of Exegol on a Ubuntu Linux 22.

Steps can be:

 1. Install Exegol from sources
 2. Download the full image v1.3.2
 3. Boot with default config
 4. Run ldapdomaindump against any LDAP server
 5. MD4 error occurs

### Exegol Wrapper Version

```Text
parallels@ubuntu-linux-22-04-desktop:~$ exegol version -vvv
[*] Exegol is currently in version v4.3.1
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[+] We thank Capgemini for supporting the project (helping with dev) 🙏                                                                                       
[+] We thank HackTheBox for sponsoring the multi-arch support 💚                                                                                              
[D] Pip installation: Off 🪓                                                                                                                                  
[D] Git source installation: On ✔                                                                                                                             
[D] Host OS: Linux (Kernel)                                                                                                                                   
[D] Arch: arm64                                                                                                                                               
[D] Raw arch: aarch64                                                                                                                                         
[D] Docker desktop: Off 🪓                                                                                                                                    
[D] Shell type: Linux                                                                                                                                         
[D] Last wrapper update check: 12/02/2024
```

### Exegol container information

```Text
[*] Exegol is currently in version v4.3.1
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[+] We thank Capgemini for supporting the project (helping with dev) 🙏                                                                                       
[+] We thank HackTheBox for sponsoring the multi-arch support 💚                                                                                              
[V] Listing user configurations                                                                                                                               

🧠 User configurations                                       
┌───────────────────────────────────────────────────────────┐
│ User config file: /home/parallels/.exegol/config.yml      │
│ Private workspace: /home/parallels/.exegol/workspaces     │
│ Exegol resources: /home/parallels/Exegol/exegol-resources │
│ My resources: /home/parallels/.exegol/my-resources        │
│ Auto-check updates: On ✔                                  │
│ Auto-remove images: On ✔                                  │
│ Auto-update fs: Off 🪓                                    │
│ Default start shell: zsh                                  │
│ Shell logging method: asciinema                           │
│ Shell logging compression: On ✔                           │
│ Desktop enabled by default: Off 🪓                        │
│ Desktop default protocol: http                            │
│ Desktop default host: localhost                           │
└───────────────────────────────────────────────────────────┘

[V] Listing git repositories                                                                                                                                  
[V] Git wrapper init submodules                                                                                                                               

🐙 Project modules                         
┌───────────┬────────────┬────────────────┐
│ Name      │ Status     │ Current branch │
├───────────┼────────────┼────────────────┤
│ Wrapper   │ Up to date │ master         │
│ Images    │ Up to date │ main           │
│ Resources │ Up to date │ main           │
└───────────┴────────────┴────────────────┘


⭐ Container summary                                                                                
┌──────────────────┬───────────────────────────────────────────────────────────────────────────────┐
│             Name │ new                                                                           │
│            Image │ full - v.3.1.2 (Up to date) (arm64)                                           │
├──────────────────┼───────────────────────────────────────────────────────────────────────────────┤
│      Credentials │ root : [SNIP]                                         │
│          Desktop │ Off 🪓                                                                        │
│    Creation date │ 14/02/2024 10:19                                                              │
│              X11 │ On ✔                                                                          │
│          Network │ host                                                                          │
│         Timezone │ On ✔                                                                          │
│ Exegol resources │ On ✔ (/opt/resources)                                                         │
│     My resources │ On ✔ (/opt/my-resources)                                                      │
│    Shell logging │ Off 🪓                                                                        │
│       Privileged │ Off ✔                                                                         │
│        Workspace │ Dedicated (/workspace)                                                        │
│             Envs │ DISPLAY=:0                                                                    │
│                  │ _JAVA_AWT_WM_NONREPARENTING=1                                                 │
│                  │ QT_X11_NO_MITSHM=1                                                            │
│                  │ EXEGOL_RANDOMIZE_SERVICE_PORTS=true                                           │
│                  │ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin             │
│          Volumes │ (RW) /tmp/.X11-unix ➡ /tmp/.X11-unix                                          │
│                  │ (RO) /etc/timezone ➡ /etc/timezone                                            │
│                  │ (RO) /etc/localtime ➡ /etc/localtime                                          │
│                  │ (RW) /home/parallels/.exegol/my-resources ➡ /opt/my-resources                 │
│                  │ (RW) /home/parallels/Exegol/exegol-resources ➡ /opt/resources                 │
│                  │ (RW) /home/parallels/.exegol/workspaces/new ➡ /workspace                      │
│                  │ (RO) /home/parallels/Exegol/exegol/utils/imgsync/spawn.sh ➡ /.exegol/spawn.sh │
└──────────────────┴───────────────────────────────────────────────────────────────────────────────┘
```

### Exception

```Text
[*] Connecting to host...
[*] Binding to host
Traceback (most recent call last):
  File "/root/.local/share/pipx/venvs/ldapdomaindump/lib/python3.11/site-packages/ldap3/utils/ntlm.py", line 500, in ntowf_v2
    from Crypto.Hash import MD4  # try with the Crypto library if present
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'Crypto'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/.local/bin/ldapdomaindump", line 3, in <module>
    ldapdomaindump.main()
  File "/root/.local/share/pipx/venvs/ldapdomaindump/lib/python3.11/site-packages/ldapdomaindump/__init__.py", line 934, in main
    if not c.bind():
           ^^^^^^^^
  File "/root/.local/share/pipx/venvs/ldapdomaindump/lib/python3.11/site-packages/ldap3/core/connection.py", line 628, in bind
    response = self.do_ntlm_bind(controls)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/ldapdomaindump/lib/python3.11/site-packages/ldap3/core/connection.py", line 1394, in do_ntlm_bind
    request = bind_operation(self.version, 'SICILY_RESPONSE_NTLM', ntlm_client,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/ldapdomaindump/lib/python3.11/site-packages/ldap3/operation/bind.py", line 81, in bind_operation
    server_creds = name.create_authenticate_message()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/ldapdomaindump/lib/python3.11/site-packages/ldap3/utils/ntlm.py", line 379, in create_authenticate_message
    nt_challenge_response = self.compute_nt_response()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/ldapdomaindump/lib/python3.11/site-packages/ldap3/utils/ntlm.py", line 485, in compute_nt_response
    response_key_nt = self.ntowf_v2()
                      ^^^^^^^^^^^^^^^
  File "/root/.local/share/pipx/venvs/ldapdomaindump/lib/python3.11/site-packages/ldap3/utils/ntlm.py", line 503, in ntowf_v2
    raise e  # raise original exception
    ^^^^^^^
  File "/root/.local/share/pipx/venvs/ldapdomaindump/lib/python3.11/site-packages/ldap3/utils/ntlm.py", line 497, in ntowf_v2
    password_digest = hashlib.new('MD4', self._password.encode('utf-16-le')).digest()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.7/lib/python3.11/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.7/lib/python3.11/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type MD4
```

### Additional context

Running something like DPAT (https://github.com/clr2of8/DPAT) gives me the following error:

```
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.11.7/lib/python3.11/hashlib.py", line 160, in __hash_new
    return _hashlib.new(name, data, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_hashlib.UnsupportedDigestmodError: [digital envelope routines] unsupported

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/my-resources/DPAT/dpat.py", line 283, in <module>
    password = crack_it(pair[0], lm_pwd)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/my-resources/DPAT/dpat.py", line 159, in crack_it
    hash = hashlib.new('md4', pwd_guess.encode('utf-16le')).hexdigest()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.7/lib/python3.11/hashlib.py", line 166, in __hash_new
    return __get_builtin_constructor(name)(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.7/lib/python3.11/hashlib.py", line 123, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md4
```

**Comment by ShutdownRepo** [comment]
Please try `pipx inject ldapdomaindump pycryptodome`

**Comment by DeserranoJorden** [comment]
This generates the following error:

```
Fatal error from pip prevented installation. Full pip output in file:
    /root/.local/state/pipx/log/cmd_2024-02-14_11.03.24_pip_errors.log

Some possibly relevant errors from pip install:
    ERROR: Could not find a version that satisfies the requirement pycryptdome (from versions: none)
    ERROR: No matching distribution found for pycryptdome
Error installing pycryptdome.
```

Even tho pycryptdome can be found at:
` /root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/pycryptodome-3.20.0.dist-info  `

**Comment by ShutdownRepo** [comment]
> This generates the following error:
> 
> ```
> Fatal error from pip prevented installation. Full pip output in file:
>     /root/.local/state/pipx/log/cmd_2024-02-14_11.03.24_pip_errors.log
> 
> Some possibly relevant errors from pip install:
>     ERROR: Could not find a version that satisfies the requirement pycryptdome (from versions: none)
>     ERROR: No matching distribution found for pycryptdome
> Error installing pycryptdome.
> ```
> 
> Even tho pycryptdome can be found at: `/root/.pyenv/versions/3.11.7/lib/python3.11/site-packages/pycryptodome-3.20.0.dist-info `

you did a typoe `pycryptdome` --> `pycryptodome`

**Comment by DeserranoJorden** [comment]
Oh damm, my apologies. I ran this command like 4 times and didn't notice.

This fixes the issue, thanks!

**Comment by ShutdownRepo** [comment]
Closing
@DeserranoJorden can you list the tools where you needed this fix, so that we add them upstream?
