### ISSUE TITLE
[BUG] Neo4j server crash

### ISSUE THREAD

**Issue by VincentSan** [ThePorgs/Exegol-images#370]
### Describe the bug

Hi 👋,

I have problem with neo4j server.
I use the last version of ad image. 

Service status :
```
[Jul 12, 2024 - 16:51:25 (UTC)] exegol-test /workspace # service neo4j restart
Neo4j is not running.
Directories in use:
home:         /var/lib/neo4j
config:       /etc/neo4j
logs:         /var/log/neo4j
plugins:      /var/lib/neo4j/plugins
import:       /var/lib/neo4j/import
data:         /var/lib/neo4j/data
certificates: /var/lib/neo4j/certificates
licenses:     /var/lib/neo4j/licenses
run:          /var/lib/neo4j/run
Starting Neo4j.
WARNING! You are using an unsupported Java runtime.
* Please use Oracle(R) Java(TM) 11, OpenJDK(TM) 11 to run Neo4j.
* Please see https://neo4j.com/docs/ for Neo4j installation instructions.
Started neo4j (pid:2971). It is available at http://localhost:7474
There may be a short delay until the server is ready.
[Jul 12, 2024 - 16:51:31 (UTC)] exegol-test /workspace # service neo4j status
neo4j is not running ... failed!
```

### Steps To Reproduce

1. service neo4j restart
2. service neo4j status

### Exegol Wrapper Version

```Text
[*] Exegol is currently in version v4.3.4
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[D] Pip installation: On ✔
[D] Git source installation: Off 🪓
[D] Host OS: Mac (Orbstack)
[D] Arch: arm64
[D] Docker desktop: Off 🪓
[D] Shell type: Mac
[D] Last wrapper update check: 11/07/2024

[*] Exegol is currently in version v4.3.4
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
```

### Exegol container information

```Text
[*] Exegol is currently in version v4.3.4
[*] Exegol Discord serv.: https://discord.gg/cXThyp7D6P
[*] Exegol documentation: https://exegol.rtfd.io/
[V] Listing user configurations

🧠 User configurations
┌────────────────────────────────────────────────────────┐
│ User config file: /Users/fuko/.exegol/config.yml       │
│ Private workspace: /Users/fuko/.exegol/workspaces      │
│ Exegol resources: /Users/fuko/.exegol/exegol-resources │
│ My resources: /Users/fuko/.exegol/my-resources         │
│ Auto-check updates: On ✔                               │
│ Auto-remove images: On ✔                               │
│ Auto-update fs: Off 🪓                                 │
│ Default start shell: zsh                               │
│ Shell logging method: asciinema                        │
│ Shell logging compression: On ✔                        │
│ Desktop enabled by default: Off 🪓                     │
│ Desktop default protocol: http                         │
│ Desktop default host: localhost                        │
└────────────────────────────────────────────────────────┘

[V] Listing git repositories
[!] Exegol has not been installed via git clone. Skipping wrapper auto-update operation.
[*] If you have installed Exegol with pip, check for an update with the command pip3 install exegol --upgrade
[!] Exegol has not been installed via git clone. Skipping wrapper auto-update operation.
[*] If you have installed Exegol with pip, check for an update with the command pip3 install exegol --upgrade

🐙 Project modules
┌───────────┬───────────────┬────────────────┐
│ Name      │ Status        │ Current branch │
├───────────┼───────────────┼────────────────┤
│ Wrapper   │ Not installed │ ? 🤷           │
│ Images    │ Not installed │ ? 🤷           │
│ Resources │ Up to date    │ main           │
└───────────┴───────────────┴────────────────┘


⭐ Container summary
┌──────────────────┬──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│             Name │ test                                                                                                                     │
│            Image │ ad - v.3.1.4 (Up to date) (arm64)                                                                                        │
├──────────────────┼──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤
│      Credentials │ root : IH2WOEX035U0Pz4CrZd02wONcxVG3T                                                                                    │
│   Remote Desktop │ Off 🪓                                                                                                                   │
│    Creation date │ 12/07/2024 18:51                                                                                                         │
│      Console GUI │ On ✔ (X11)                                                                                                               │
│          Network │ host                                                                                                                     │
│         Timezone │ Off 🪓                                                                                                                   │
│ Exegol resources │ On ✔ (/opt/resources)                                                                                                    │
│     My resources │ On ✔ (/opt/my-resources)                                                                                                 │
│    Shell logging │ Off 🪓                                                                                                                   │
│       Privileged │ Off ✔                                                                                                                    │
│        Workspace │ Dedicated (/workspace)                                                                                                   │
│             Envs │ DISPLAY=host.docker.internal:0                                                                                           │
│                  │ _JAVA_AWT_WM_NONREPARENTING=1                                                                                            │
│                  │ QT_X11_NO_MITSHM=1                                                                                                       │
│                  │ EXEGOL_RANDOMIZE_SERVICE_PORTS=true                                                                                      │
│                  │ PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                        │
│          Volumes │ (RW) /Users/fuko/.exegol/my-resources ➡ /opt/my-resources                                                                │
│                  │ (RW) /Users/fuko/.exegol/exegol-resources ➡ /opt/resources                                                               │
│                  │ (RW) /Users/fuko/.exegol/workspaces/test ➡ /workspace                                                                    │
│                  │ (RO) /Users/fuko/.local/pipx/venvs/exegol/lib/python3.12/site-packages/exegol/utils/imgsync/spawn.sh ➡ /.exegol/spawn.sh │
└──────────────────┴──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

### Additional context

```Text
# Neo4j Log
OpenJDK 64-Bit Server VM warning: Option UseBiasedLocking was deprecated in version 15.0 and will likely be removed in a future release.
2024-07-12 16:51:32.177+0000 INFO  Starting...
Exception in thread "main" java.lang.LinkageError: Cannot to link java.nio.DirectByteBuffer
	at org.neo4j.internal.unsafe.UnsafeUtil.<clinit>(UnsafeUtil.java:128)
	at org.neo4j.memory.RuntimeInternals.guessHeaderSize(RuntimeInternals.java:158)
	at org.neo4j.memory.RuntimeInternals.<clinit>(RuntimeInternals.java:53)
	at org.neo4j.memory.HeapEstimator.<clinit>(HeapEstimator.java:103)
	at org.neo4j.internal.collector.RecentQueryBuffer.<clinit>(RecentQueryBuffer.java:37)
	at org.neo4j.graphdb.factory.module.GlobalModule.<init>(GlobalModule.java:212)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.createGlobalModule(DatabaseManagementServiceFactory.java:272)
	at org.neo4j.graphdb.facade.DatabaseManagementServiceFactory.build(DatabaseManagementServiceFactory.java:133)
	at org.neo4j.server.CommunityBootstrapper.createNeo(CommunityBootstrapper.java:36)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:142)
	at org.neo4j.server.NeoBootstrapper.start(NeoBootstrapper.java:95)
	at org.neo4j.server.CommunityEntryPoint.main(CommunityEntryPoint.java:34)
Caused by: java.lang.IllegalAccessException: module java.base does not open java.nio to unnamed module @71cef2ed
	at java.base/java.lang.invoke.MethodHandles.privateLookupIn(MethodHandles.java:259)
	at org.neo4j.internal.unsafe.UnsafeUtil.<clinit>(UnsafeUtil.java:111)
	... 11 more
2024-07-12 16:51:32.245+0000 INFO  Neo4j Server shutdown initiated by request
2024-07-12 16:51:32.245+0000 INFO  Stopped.
```

**Comment by QU35T-code** [comment]
Hello @VincentSan,

You must use the command `neo4j` and not `service` because there is an alias of the neo4j command with the correct version of java.

```bash
root@exegol-repro /workspace # neo4j restart                                  
Neo4j is not running.
Directories in use:
home:         /var/lib/neo4j
config:       /etc/neo4j
logs:         /var/log/neo4j
plugins:      /var/lib/neo4j/plugins
import:       /var/lib/neo4j/import
data:         /var/lib/neo4j/data
certificates: /var/lib/neo4j/certificates
licenses:     /var/lib/neo4j/licenses
run:          /var/lib/neo4j/run
Starting Neo4j.
Started neo4j (pid:4806). It is available at http://localhost:7474
There may be a short delay until the server is ready.
```

```bash
root@exegol-repro /workspace # neo4j status 
Neo4j is running at pid 4806
```
